name: Build and Publish Jar Artifact

on:
  push:
    branches:
      - '**'
    paths:
      - '.github/workflows/push.yml'
      - 'gradle'
      - 'src/**'
      - 'build.gradle'
      - 'gradle.properties'
      - 'gradlew'
      - 'gradlew.bat'
      - 'settings.gradle'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          
      - name: Checkout Messager dependency
        uses: actions/checkout@v3
        with:
          repository: Pickaria/Messager
          path: Messager
          ref: 1.0-SNAPSHOT

      - name: Publish Messager to mavenLocal
        working-directory: Messager
        run: ./gradlew publishToMavenLocal
        
      - name: Build Jar
        run: ./gradlew jar

      - name: Upload Jar Artifact
        uses: actions/upload-artifact@v4
        with:
          name: jar-artifact
          path: build/libs/*.jar
