name: Build and Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Checkout Messager dependency
        uses: actions/checkout@v3
        with:
          repository: Pickaria/Messager
          path: Messager
          ref: 1.0-SNAPSHOT

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          
      - name: Publish Messager to mavenLocal
        working-directory: Messager
        run: ./gradlew publishToMavenLocal
        
      - name: Build Jar
        run: ./gradlew jar

      - name: Find Jar file
        id: find_jar
        run: |
          jar_path=$(ls build/libs/*.jar)
          echo "jar_path=$jar_path" >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.find_jar.outputs.jar_path }}
